import { LocalizedPricingPlan, LocalizedFaqItem, I18nString } from "./types";

export const pricingContent = {
  eyebrow: {
    en: "TRANSPARENT VALUE-BASED PRICING",
    es: "PRECIOS TRANSPARENTES BASADOS EN VALOR",
  },
  title: {
    en: "Scale Your Docket Marketing with Predictable ROI",
    es: "Escale su Mercadeo Legal con Retorno de Inversión Predecible",
  },
  subtitle: {
    en: "Every plan includes unlimited team members, raw native desktop speed, and live court docket coverage. Scale leads and enrichments on your terms.",
    es: "Cada plan incluye usuarios de equipo ilimitados, velocidad nativa de escritorio y cobertura de expedientes en vivo. Escale casos según sus necesidades.",
  },
  unlimitedUsersCallout: {
    en: "Zero per-seat licensing fees. Add your entire legal team, paralegals, and marketing coordinators at no extra cost.",
    es: "Cero costos por usuario. Agregue a todo su equipo legal, asistentes y coordinadores de mercadeo sin costo adicional.",
  },
  billingToggle: {
    monthly: { en: "Monthly Billing", es: "Facturación Mensual" },
    annual: { en: "Annual Billing", es: "Facturación Anual" },
    saveBadge: { en: "Lock in your rates", es: "Asegure sus tarifas" },
  },
  plans: [
    {
      id: "free",
      name: { en: "Free", es: "Gratis" },
      priceMonthly: 0,
      priceAnnualMonthly: 0,
      costPerLead: "$0.60 / extra lead",
      monthlyLeads: 50,
      dailyLeads: 5,
      tagline: {
        en: "50 included leads monthly. Expand anytime with on-demand packs.",
        es: "50 casos incluidos al mes. Amplíe cuando desee con paquetes adicionales.",
      },
      popular: false,
      unlimitedUsers: true,
      features: [
        { en: "50 monthly leads & enrichments (5/day)", es: "50 casos y enriquecimientos / mes (5/día)" },
        { en: "Pay-as-you-go: Add leads anytime ($0.60/ea)", es: "Pago por uso: Agregue casos adicionales ($0.60 c/u)" },
        { en: "Unlimited firm members & user logins", es: "Usuarios y miembros de equipo ilimitados" },
        { en: "Full Pennsylvania court docket search", es: "Búsqueda completa en tribunales de Pensilvania" },
        { en: "5 CSV exports daily", es: "5 exportaciones CSV diarias" },
        { en: "Webhooks & automation triggers included", es: "Webhooks y disparadores incluidos sin costo" },
        { en: "25 MB local encrypted storage", es: "25 MB de almacenamiento cifrado local" },
      ],
      cta: { en: "Download Free App", es: "Descargar App Gratis" },
      ctaHref: "/download",
    },
    {
      id: "starter",
      name: { en: "Starter", es: "Inicial" },
      priceMonthly: 300,
      priceAnnualMonthly: 300,
      costPerLead: "$0.60 / lead",
      monthlyLeads: 500,
      dailyLeads: 50,
      tagline: {
        en: "Ideal for solo practitioners and focused county practices.",
        es: "Ideal para abogados independientes y prácticas enfocadas por condado.",
      },
      popular: false,
      unlimitedUsers: true,
      features: [
        { en: "500 monthly leads & enrichments (50/day)", es: "500 casos y enriquecimientos / mes (50/día)" },
        { en: "10 AI letters daily (100 / 6 mo)", es: "10 cartas IA diarias (100 / 6 meses)" },
        { en: "Unlimited team members & seats", es: "Usuarios y miembros de equipo ilimitados" },
        { en: "Full Pennsylvania court docket search", es: "Búsqueda completa en tribunales de Pensilvania" },
        { en: "25 CSV exports daily", es: "25 exportaciones CSV diarias" },
        { en: "Webhooks & automation triggers included", es: "Webhooks y disparadores incluidos sin costo" },
        { en: "500 MB cloud synchronized storage", es: "500 MB de almacenamiento sincronizado" },
      ],
      cta: { en: "Get Starter", es: "Elegir Inicial" },
      ctaHref: "/download",
    },
    {
      id: "pro",
      name: { en: "Professional", es: "Profesional" },
      priceMonthly: 3000,
      priceAnnualMonthly: 3000,
      costPerLead: "$0.60 / lead",
      monthlyLeads: 5000,
      dailyLeads: 500,
      tagline: {
        en: "For active law firms dominating regional court dockets.",
        es: "Para bufetes activos que dominan los expedientes judiciales regionales.",
      },
      popular: true,
      unlimitedUsers: true,
      features: [
        { en: "5,000 monthly leads & enrichments (500/day)", es: "5,000 casos y enriquecimientos / mes (500/día)" },
        { en: "100 AI letters daily (1,000 / 6 mo)", es: "100 cartas IA diarias (1,000 / 6 meses)" },
        { en: "Unlimited team members & seats", es: "Usuarios y miembros de equipo ilimitados" },
        { en: "USPS CASS direct-mail presorting (cut postage 30-50%)", es: "Preclasificación CASS de USPS (ahorre 30-50% en sellos)" },
        { en: "100 CSV exports daily", es: "100 exportaciones CSV diarias" },
        { en: "Webhooks & full REST / GraphQL API", es: "Webhooks y API REST / GraphQL completa" },
        { en: "10 GB cloud storage (10,240 MB)", es: "10 GB de almacenamiento en la nube" },
      ],
      cta: { en: "Start Professional", es: "Comenzar Profesional" },
      ctaHref: "/download",
    },
    {
      id: "scale",
      name: { en: "Scale", es: "Escala" },
      priceMonthly: 5500,
      priceAnnualMonthly: 5500,
      costPerLead: "$0.55 / lead",
      monthlyLeads: 10000,
      dailyLeads: 1000,
      tagline: {
        en: "High-volume direct-mail automation for premier litigation firms.",
        es: "Automatización de alto volumen para bufetes líderes de litigación.",
      },
      popular: false,
      unlimitedUsers: true,
      features: [
        { en: "10,000 monthly leads & enrichments (1,000/day)", es: "10,000 casos y enriquecimientos / mes (1,000/día)" },
        { en: "250 AI letters daily (2,500 / 6 mo)", es: "250 cartas IA diarias (2,500 / 6 meses)" },
        { en: "Unlimited team members & seats", es: "Usuarios y miembros de equipo ilimitados" },
        { en: "Bulk batch USPS presort automation & tray barcoding", es: "Preclasificación postal por lotes y códigos de barras" },
        { en: "250 CSV exports daily", es: "250 exportaciones CSV diarias" },
        { en: "Webhooks & dedicated priority queue", es: "Webhooks y cola prioritaria dedicada" },
        { en: "High-capacity dedicated cloud storage", es: "Almacenamiento en la nube dedicado de alta capacidad" },
      ],
      cta: { en: "Start Scale Plan", es: "Elegir Plan Escala" },
      ctaHref: "/download",
    },
  ] as LocalizedPricingPlan[],
  enterpriseCallout: {
    badge: { en: "CUSTOM ENTERPRISE", es: "EMPRESARIAL A MEDIDA" },
    title: { en: "Need a Custom Statewide or Multi-Branch Plan?", es: "¿Necesita un Plan a Medida para Múltiples Sucursales?" },
    description: {
      en: "Every litigation enterprise has unique requirements. Rather than forcing a rigid tier, we tailor custom solutions: dedicated docket monitoring, bespoke CRM integrations (Clio, MyCase, Salesforce), isolated database clusters, and 99.9% SLAs.",
      es: "Cada operación legal tiene requerimientos únicos. En lugar de un plan rígido, adaptamos soluciones a medida: monitoreo dedicado de expedientes, integraciones CRM personalizadas (Clio, MyCase, Salesforce), bases de datos aisladas y SLA del 99.9%.",
    },
    cta: { en: "Talk to Our Engineering Team", es: "Hablar con Nuestro Equipo" },
    ctaHref: "mailto:support@docketlinks.com?subject=DocketLinks%20Enterprise%20Custom%20Inquiry",
  },
  liveRatesBadge: {
    en: "Live In-App Rates",
    es: "Tarifas en tiempo real en la aplicación",
  },
  cardLabels: {
    popularBadge: { en: "Most Popular", es: "Más Popular" },
    payAsYouGoBadge: { en: "Pay-As-You-Go", es: "Pago por Uso" },
    soloPracticeBadge: { en: "Solo Practice", es: "Práctica Individual" },
    highVolumeBadge: { en: "High Volume", es: "Alto Volumen" },
    includedMonthly: { en: "/mo (50 leads)", es: "/mes (50 casos)" },
    monthlyInterval: { en: "/mo", es: "/mes" },
    annualInterval: { en: "/mo", es: "/mes" },
    saveBadge: { en: "Lock in your rates", es: "Asegure sus tarifas" },
    leadsPerMonth: { en: "leads / mo", es: "casos / mes" },
    leadUnit: { en: "lead", es: "caso" },
    whatsIncluded: { en: "What's included:", es: "Qué incluye este plan:" },
  },
  addonPackSection: {
    badge: { en: "On-Demand Add-On Credits", es: "Paquetes Adicionales a Pedido" },
    title: { en: "Lead & Enrichment Add-On Packs", es: "Paquete de Casos y Enriquecimientos" },
    description: {
      en: "Need extra lead volume for high-impact court docket campaigns? Add on-demand verified leads and phone/address enrichments anytime. Credits never expire and sync directly inside DocketLinks.",
      es: "Disponibles en cualquier plan cuando necesite volumen adicional para campañas de correo directo de alto impacto. Los créditos nunca caducan y se activan directamente en la aplicación de escritorio.",
    },
    features: [
      { en: "Minimum 100 leads", es: "Mínimo 100 casos" },
      { en: "Credits never expire", es: "Sin fecha de vencimiento" },
      { en: "Compatible with all plans", es: "Válido en cualquier plan" },
    ],
    quantityLabel: { en: "Select Lead Quantity:", es: "Seleccionar Cantidad de Casos:" },
    unitRateLabel: { en: "Unit rate:", es: "Tarifa unitaria:" },
    leadUnit: { en: "lead", es: "caso" },
    leadsAndEnrichments: { en: "leads & enrichments", es: "casos y enriquecimientos" },
    oneTime: { en: "one-time", es: "pago único" },
    cta: { en: "Get Add-Ons in Desktop App", es: "Gestionar en la App de Escritorio" },
  },
  comparisonTable: {
    title: { en: "Detailed Feature Comparison", es: "Comparativa Detallada de Planes" },
    subtitle: {
      en: "Compare exact technical quotas, automation tools, and capabilities",
      es: "Vea todas las capacidades y cuotas exactas disponibles en cada nivel de servicio",
    },
    featureCol: { en: "Feature", es: "Característica" },
    freeCol: { en: "Free / Pay-As-You-Go", es: "Gratis / Pago por Uso" },
    rows: {
      costPerLead: { en: "Cost per lead", es: "Costo estimado por caso" },
      extraLeadRate: { en: "$0.60 / extra lead", es: "$0.60 / adicional" },
      monthlyLeads: { en: "Monthly leads & enrichments", es: "Casos y enriquecimientos / mes" },
      dailyLeads: { en: "Daily lead quota", es: "Límite diario de casos" },
      dailyExports: { en: "Daily CSV exports", es: "Exportaciones CSV diarias" },
      aiLetters: { en: "AI letter generation", es: "Cartas generadas por IA" },
      aiLettersStarter: { en: "10 / day (100 / 6mo)", es: "10 / día (100 / 6 meses)" },
      aiLettersPro: { en: "100 / day (1,000 / 6mo)", es: "100 / día (1,000 / 6 meses)" },
      aiLettersScale: { en: "250 / day (2,500 / 6mo)", es: "250 / día (2,500 / 6 meses)" },
      webhooks: { en: "Webhooks & triggers included", es: "Webhooks y disparadores incluidos" },
      teamMembers: { en: "Team member logins", es: "Miembros y usuarios de equipo" },
      unlimited: { en: "Unlimited", es: "Ilimitados" },
      cloudStorage: { en: "Cloud storage quota", es: "Almacenamiento en la nube" },
      dedicatedCloud: { en: "Dedicated Cloud", es: "Alta Capacidad" },
      uspsPresort: { en: "USPS CASS Direct Mail Presort", es: "Preclasificación CASS USPS (Ahorro 30-50%)" },
      apiAccess: { en: "Full REST/GraphQL API access", es: "Acceso a API REST / GraphQL" },
      nativeRust: { en: "High-performance native desktop app", es: "Aplicación de escritorio nativa de alto rendimiento" },
    },
  },
  faqs: [
    {
      question: {
        en: "What is the difference between a lead and an enrichment?",
        es: "¿Cuál es la diferencia entre un prospecto (lead) y un enriquecimiento (enrichment)?",
      },
      answer: {
        en: "A lead is the raw court case filing (docket number, defendant name, charges, filing date, and court jurisdiction). Raw court records do not include verified defendant addresses, phone numbers, or email contact details. This is where DocketLinks proprietary software shines: we cross-reference multiple public record sources to determine verified mailing addresses, phone numbers, and email contact info for the defendant. Attorneys can then download these enriched leads and use them for direct-mail letters or email solicitation to individuals facing active legal proceedings with high buyer intent.",
        es: "Un prospecto (lead) representa los datos crudos del expediente judicial (número de caso, nombre del demandado o imputado, cargos, fecha y juzgado). Los registros judiciales no incluyen direcciones postales, teléfonos ni correos electrónicos. Aquí es donde nuestro software propietario se destaca: cruzamos múltiples registros públicos para determinar direcciones postales, teléfonos y correos verificados del acusado. Los abogados pueden descargar estos prospectos enriquecidos y utilizarlos en cartas de correo directo o correos de captación dirigidos a personas que enfrentan procesos judiciales con alta intención de contratación.",
      },
    },
    {
      question: {
        en: "Why are users unlimited on all plans?",
        es: "¿Por qué los usuarios son ilimitados en todos los planes?",
      },
      answer: {
        en: "We believe per-seat pricing penalizes legal teamwork. Whether your firm has 2 attorneys or 40 paralegals and marketing assistants, everyone can log in, collaborate, and share saved searches without paying an extra dime.",
        es: "Creemos que cobrar por usuario penaliza la colaboración. Ya sea que su bufete cuente con 2 abogados o 40 asistentes legales y coordinadores de mercadeo, todos pueden ingresar y compartir filtros sin costo adicional.",
      },
    },
    {
      question: {
        en: "How does the lead cost scale down?",
        es: "¿Cómo disminuye el costo por caso a medida que escalo?",
      },
      answer: {
        en: "Our lower plans start at an accessible $0.65 per lead, stepping down to $0.60 on Professional, and $0.55 per lead at the 10,000/month Scale tier. Custom volume pricing (< $0.50/lead) is available for 25,000+ leads.",
        es: "Nuestros planes iniciales comienzan a $0.65 por caso, reduciéndose a $0.60 en Profesional y $0.55 por caso en el nivel Escala de 10,000/mes. Ofrecemos precios por volumen inferiores a $0.50 para más de 25,000 casos.",
      },
    },
    {
      question: {
        en: "What is USPS CASS presorting and how does it save 30-50% on postage?",
        es: "¿Qué es la preclasificación CASS de USPS y cómo ahorra 30-50% en franqueo?",
      },
      answer: {
        en: "DocketLinks includes automated CASS address standardization and postal tray sorting. By pre-sorting your recipient addresses into USPS carrier routes and barcodes, you qualify for commercial automation rates, slashing first-class postage by 30-50% per mailpiece.",
        es: "DocketLinks incluye estandarización de direcciones CASS y ordenamiento por bandejas postales. Al preclasificar sus destinatarios en códigos de barras y rutas de entrega de USPS, califica para tarifas comerciales con descuentos del 30-50% por carta.",
      },
    },
    {
      question: {
        en: "Can multiple lawyers accidentally claim the same lead?",
        es: "¿Pueden varios abogados reclamar por accidente el mismo caso?",
      },
      answer: {
        en: "No. Our Lead Claiming & Collision Guard locks claimed leads immediately across your entire firm tenant. Once an attorney or team member claims a docket lead, other members see the claim status and assigned notes, preventing embarrassing duplicate client solicitations.",
        es: "No. Nuestro sistema de Reclamo y Control de Colisiones bloquea el caso de inmediato en toda su organización. En cuanto un miembro reclama un expediente, los demás ven el estado y notas asignadas, evitando contactos duplicados.",
      },
    },
  ] as LocalizedFaqItem[],
};
