import { LocalizedPricingPlan, LocalizedFaqItem, I18nString } from "./types";

export const pricingContent = {
  eyebrow: {
    en: "TRANSPARENT VALUE-BASED PRICING",
    es: "PRECIOS TRANSPARENTES BASADOS EN VALOR",
  },
  title: {
    en: "Scale Your Docket Marketing with Predictable ROI",
    es: "Escale su Mercadeo Legal con Retorno de Inversión Predecible",
  },
  subtitle: {
    en: "Every plan includes unlimited team members, raw native desktop speed, and live court docket coverage. Scale leads and enrichments on your terms.",
    es: "Cada plan incluye usuarios de equipo ilimitados, velocidad nativa de escritorio y cobertura de expedientes en vivo. Escale casos según sus necesidades.",
  },
  unlimitedUsersCallout: {
    en: "Zero per-seat licensing fees. Add your entire legal team, paralegals, and marketing coordinators at no extra cost.",
    es: "Cero costos por usuario. Agregue a todo su equipo legal, asistentes y coordinadores de mercadeo sin costo adicional.",
  },
  billingToggle: {
    monthly: { en: "Monthly Billing", es: "Facturación Mensual" },
    annual: { en: "Annual Billing", es: "Facturación Anual" },
    saveBadge: { en: "Save up to 20%", es: "Ahorre hasta un 20%" },
  },
  plans: [
    {
      id: "free",
      name: { en: "Free", es: "Gratis" },
      priceMonthly: 0,
      priceAnnualMonthly: 0,
      costPerLead: "$0 / lead",
      monthlyLeads: 25,
      dailyLeads: 5,
      tagline: {
        en: "Test our real-time docket feed and experience desktop speed.",
        es: "Pruebe nuestro flujo de expedientes y experimente la velocidad nativa.",
      },
      popular: false,
      unlimitedUsers: true,
      features: [
        { en: "25 leads & 25 enrichments / month (5/day)", es: "25 casos y 25 enriquecimientos / mes (5/día)" },
        { en: "Unlimited firm members & user logins", es: "Usuarios y miembros de equipo ilimitados" },
        { en: "Full Pennsylvania court docket search", es: "Búsqueda completa en tribunales de Pensilvania" },
        { en: "Statute and charge grade filters", es: "Filtros por estatuto y gravedad de delito" },
        { en: "5 CSV exports daily", es: "5 exportaciones CSV diarias" },
        { en: "25 MB encrypted local storage", es: "25 MB de almacenamiento cifrado local" },
        { en: "Community support & guides", es: "Soporte comunitario y guías" },
      ],
      cta: { en: "Download Free App", es: "Descargar App Gratis" },
      ctaHref: "/download",
    },
    {
      id: "starter",
      name: { en: "Starter", es: "Inicial" },
      priceMonthly: 325,
      priceAnnualMonthly: 275,
      costPerLead: "$0.65 / lead",
      monthlyLeads: 500,
      dailyLeads: 50,
      tagline: {
        en: "Ideal for solo practitioners and focused county practices.",
        es: "Ideal para abogados independientes y prácticas enfocadas por condado.",
      },
      popular: false,
      unlimitedUsers: true,
      features: [
        { en: "500 leads & 500 enrichments / month (50/day)", es: "500 casos y 500 enriquecimientos / mes (50/día)" },
        { en: "Unlimited team members & seats", es: "Usuarios y miembros de equipo ilimitados" },
        { en: "Address validation & gender enrichment", es: "Validación de dirección y enriquecimiento" },
        { en: "10 saved filter profiles", es: "10 perfiles de búsqueda guardados" },
        { en: "1 automated webhook trigger", es: "1 webhook de automatización" },
        { en: "25 CSV exports daily", es: "25 exportaciones CSV diarias" },
        { en: "500 MB cloud synchronized storage", es: "500 MB de almacenamiento sincronizado" },
        { en: "Standard email support", es: "Soporte por correo electrónico" },
      ],
      cta: { en: "Get Starter", es: "Elegir Inicial" },
      ctaHref: "/download",
    },
    {
      id: "pro",
      name: { en: "Professional", es: "Profesional" },
      priceMonthly: 1200,
      priceAnnualMonthly: 999,
      costPerLead: "$0.60 / lead",
      monthlyLeads: 2000,
      dailyLeads: 200,
      tagline: {
        en: "For active law firms dominating regional court dockets.",
        es: "Para bufetes activos que dominan los expedientes judiciales regionales.",
      },
      popular: true,
      unlimitedUsers: true,
      features: [
        { en: "2,000 leads & 2,000 enrichments / month (200/day)", es: "2,000 casos y 2,000 enriquecimientos / mes (200/día)" },
        { en: "Unlimited team members & seats", es: "Usuarios y miembros de equipo ilimitados" },
        { en: "USPS CASS direct-mail presorting (cut postage 30-50%)", es: "Preclasificación CASS de USPS (ahorre 30-50% en sellos)" },
        { en: "Multi-attorney lead claiming & collision locks", es: "Bloqueo de colisión y asignación de casos por abogado" },
        { en: "50 saved filter profiles", es: "50 perfiles de búsqueda guardados" },
        { en: "5 automated webhook endpoints", es: "5 endpoints para webhooks" },
        { en: "100 CSV exports daily", es: "100 exportaciones CSV diarias" },
        { en: "Full REST & GraphQL API access", es: "Acceso completo a API REST y GraphQL" },
        { en: "2 GB encrypted cloud storage", es: "2 GB de almacenamiento cifrado en la nube" },
        { en: "Priority queue & live chat support", es: "Cola prioritaria y soporte por chat" },
      ],
      cta: { en: "Start Professional", es: "Comenzar Profesional" },
      ctaHref: "/download",
    },
    {
      id: "scale",
      name: { en: "Scale", es: "Escala" },
      priceMonthly: 5500,
      priceAnnualMonthly: 4590,
      costPerLead: "$0.55 / lead",
      monthlyLeads: 10000,
      dailyLeads: 1000,
      tagline: {
        en: "High-volume direct-mail automation for premier litigation firms.",
        es: "Automatización de alto volumen para bufetes líderes de litigación.",
      },
      popular: false,
      unlimitedUsers: true,
      features: [
        { en: "10,000 leads & 10,000 enrichments / month (1,000/day)", es: "10,000 casos y 10,000 enriquecimientos / mes (1,000/día)" },
        { en: "Unlimited team members & seats", es: "Usuarios y miembros de equipo ilimitados" },
        { en: "Bulk batch USPS presort automation & tray barcoding", es: "Preclasificación postal por lotes y códigos de barras" },
        { en: "Custom export schema & direct CRM sync", es: "Mapeo de campos personalizado y sincronización CRM" },
        { en: "Unlimited saved filter presets", es: "Perfiles de filtro ilimitados" },
        { en: "25 webhook automation pipelines", es: "25 pipelines de automatización webhook" },
        { en: "Unlimited exports daily", es: "Exportaciones diarias ilimitadas" },
        { en: "High-throughput dedicated scraper queue", es: "Cola de extracción dedicada de alto rendimiento" },
        { en: "10 GB encrypted cloud storage", es: "10 GB de almacenamiento cifrado" },
        { en: "Dedicated account manager & phone onboarding", es: "Gerente de cuenta dedicado y capacitación telefónica" },
      ],
      cta: { en: "Start Scale Plan", es: "Elegir Plan Escala" },
      ctaHref: "/download",
    },
    {
      id: "enterprise",
      name: { en: "Enterprise", es: "Empresarial" },
      priceMonthly: 0,
      priceAnnualMonthly: 0,
      costPerLead: "< $0.50 / lead",
      monthlyLeads: 25000,
      dailyLeads: 2500,
      tagline: {
        en: "Tailored infrastructure for statewide networks and legal operations.",
        es: "Infraestructura personalizada para redes estatales y operaciones legales.",
      },
      popular: false,
      unlimitedUsers: true,
      features: [
        { en: "25,000+ leads / month with custom volume pricing", es: "Más de 25,000 casos / mes con tarifas por volumen" },
        { en: "Unlimited team members & multi-office branching", es: "Usuarios ilimitados y sucursales multi-oficina" },
        { en: "Isolated dedicated database & custom scraper rules", es: "Base de datos aislada y reglas de extracción a medida" },
        { en: "Tenant-level customer-managed encryption master key", es: "Clave maestra de cifrado administrada por el cliente" },
        { en: "Custom integrations (Clio, MyCase, Filevine, Salesforce)", es: "Integraciones a medida (Clio, MyCase, Filevine, Salesforce)" },
        { en: "99.9% uptime SLA & 24/7 dedicated engineering support", es: "SLA del 99.9% y soporte de ingeniería 24/7" },
      ],
      cta: { en: "Talk to Our Team", es: "Hablar con el Equipo" },
      ctaHref: "mailto:support@docketlinks.com?subject=DocketLinks%20Enterprise%20Inquiry",
    },
  ] as LocalizedPricingPlan[],
  faqs: [
    {
      question: {
        en: "Why are users unlimited on all plans?",
        es: "¿Por qué los usuarios son ilimitados en todos los planes?",
      },
      answer: {
        en: "We believe per-seat pricing penalizes legal teamwork. Whether your firm has 2 attorneys or 40 paralegals and marketing assistants, everyone can log in, collaborate, and share saved searches without paying an extra dime.",
        es: "Creemos que cobrar por usuario penaliza la colaboración. Ya sea que su bufete cuente con 2 abogados o 40 asistentes legales y coordinadores de mercadeo, todos pueden ingresar y compartir filtros sin costo adicional.",
      },
    },
    {
      question: {
        en: "How does the lead cost scale down?",
        es: "¿Cómo disminuye el costo por caso a medida que escalo?",
      },
      answer: {
        en: "Our lower plans start at an accessible $0.65 per lead, stepping down to $0.60 on Professional, and $0.55 per lead at the 10,000/month Scale tier. Custom volume pricing (< $0.50/lead) is available for 25,000+ leads.",
        es: "Nuestros planes iniciales comienzan a $0.65 por caso, reduciéndose a $0.60 en Profesional y $0.55 por caso en el nivel Escala de 10,000/mes. Ofrecemos precios por volumen inferiores a $0.50 para más de 25,000 casos.",
      },
    },
    {
      question: {
        en: "What is USPS CASS presorting and how does it save 30-50% on postage?",
        es: "¿Qué es la preclasificación CASS de USPS y cómo ahorra 30-50% en franqueo?",
      },
      answer: {
        en: "DocketLinks includes automated CASS address standardization and postal tray sorting. By pre-sorting your recipient addresses into USPS carrier routes and barcodes, you qualify for commercial automation rates, slashing first-class postage by 30-50% per mailpiece.",
        es: "DocketLinks incluye estandarización de direcciones CASS y ordenamiento por bandejas postales. Al preclasificar sus destinatarios en códigos de barras y rutas de entrega de USPS, califica para tarifas comerciales con descuentos del 30-50% por carta.",
      },
    },
    {
      question: {
        en: "Can multiple lawyers accidentally claim the same lead?",
        es: "¿Pueden varios abogados reclamar por accidente el mismo caso?",
      },
      answer: {
        en: "No. Our Lead Claiming & Collision Guard locks claimed leads immediately across your entire firm tenant. Once an attorney or team member claims a docket lead, other members see the claim status and assigned notes, preventing embarrassing duplicate client solicitations.",
        es: "No. Nuestro sistema de Reclamo y Control de Colisiones bloquea el caso de inmediato en toda su organización. En cuanto un miembro reclama un expediente, los demás ven el estado y notas asignadas, evitando contactos duplicados.",
      },
    },
  ] as LocalizedFaqItem[],
};
